"""empty message

Revision ID: f27883916ee0
Revises: 
Create Date: 2023-10-31 00:00:21.425925

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f27883916ee0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ammo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('calibers', sa.String(length=256), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ammo_id'), 'ammo', ['id'], unique=False)
    op.create_table('gun_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_gun_category_id'), 'gun_category', ['id'], unique=False)
    op.create_table('gun',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('barrel_type', sa.Enum('Rifled', 'Smoothbore', 'Polygonal', name='barrel_type'), nullable=False),
    sa.Column('caliber', sa.String(length=256), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('description', sa.String(length=256), nullable=False),
    sa.Column('image', sa.String(length=256), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['gun_category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gun_id'), 'gun', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_gun_id'), table_name='gun')
    op.drop_table('gun')
    op.drop_index(op.f('ix_gun_category_id'), table_name='gun_category')
    op.drop_table('gun_category')
    op.drop_index(op.f('ix_ammo_id'), table_name='ammo')
    op.drop_table('ammo')
    # ### end Alembic commands ###
