"""Initialize DB after crash

Revision ID: f42f2151609e
Revises: 
Create Date: 2023-10-15 16:29:27.211929

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f42f2151609e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gun_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_gun_category_id'), 'gun_category', ['id'], unique=False)
    op.create_table('gun',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('barrel_type', sa.Enum('Rifled', 'Smoothbore', name='barrel_type'), nullable=False),
    sa.Column('caliber', sa.String(length=256), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['gun_category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gun_id'), 'gun', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_gun_id'), table_name='gun')
    op.drop_table('gun')
    op.drop_index(op.f('ix_gun_category_id'), table_name='gun_category')
    op.drop_table('gun_category')
    # ### end Alembic commands ###
